name: neko_find
description: A mobile application to help connect people with stray and adoptable cats.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  supabase_flutter: ^2.3.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  geolocator: ^13.0.2
  image: ^4.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.20.1
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  share_plus: ^10.1.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/cat_marker.svg
    - assets/images/cat_logo.png
    - assets/icons/paw-icon.svg
    - .env
